version: '2'
services:
  producer-service:
    build: producer-service
    container_name: producer-service
    ports:
      - 8001:8080
    environment:
      - SPRING_PROFILES_ACTIVE=localstack
    depends_on:
      - postgres
      - localstack
    links:
      - localstack
    restart: on-failure
  consumer-service:
    build: consumer-service
    container_name: consumer-service
    ports:
      - 8002:8080
    environment:
      - SPRING_PROFILES_ACTIVE=localstack
    depends_on:
      - localstack
    links:
      - localstack
    restart: on-failure
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=sqs,sns
      - HOSTNAME_EXTERNAL=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566-4599:4566-4599"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "./.localstack:/docker-entrypoint-initaws.d"